# Data Mining - Lab - 2

#  Numpy  &  Perform Data Exploration with Pandas

-------------------------------------------------------------------------------
## Numpy

1) NumPy (Numerical Python) is a powerful open-source library in Python used for numerical and scientific computing.<br>
2) It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them efficiently.<br>
3) NumPy is highly optimized and written in C, making it much faster than using regular Python lists for numerical operations.<br>
4) It serves as the foundation for many other Python libraries in data science and machine learning, like pandas, TensorFlow, and scikit-learn.<br>
5) With features like broadcasting, vectorization, and integration with C/C++ code, NumPy allows for cleaner and faster code in numerical computations.<br>



### Step 1. Import the Numpy library

In [5]:
import numpy as np



### Step 2. Create a 1D array of numbers

In [7]:
arr = np.arange(10)
arr

 # arange creates the array from 0 to n - 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#  if we want the array to start from 4 to and ends with 40 then
# here last is exclusive so we take 41 as last element

arr = np.arange(4, 41)
arr



array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40])

In [13]:
# if we want the static array  then ww want to passs the list in which we want the static array
arr = np.array([4, 5, 6, 14, 2, 5, 4, 6, 14])
arr

array([ 4,  5,  6, 14,  2,  5,  4,  6, 14])

In [21]:
print(type(arr))

arr.dtype

<class 'numpy.ndarray'>


dtype('int32')

### Step 3. Reshape 1D to 2D Array

In [27]:
# arr2 = np.arange(23)
# arr2

# here in the  first is first is row and the second it the column
# here size must be the row * column = size (if size if more then it gives the error also same for the less value then the row * column)
arr2 = np.arange(20).reshape(4, 5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
arr3 = np.array([[1, 2, 3], [4, 5, 6], [1, 1, 1], [4, 4, 4]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [4, 4, 4]])

### Step 4. Create a Linspace array

In [39]:
# default generate 50 numbes 
# when we want to give the random number between our numbers
#  starting element , ending element , size
arr4 = np.linspace(4, 14)
arr4

array([ 4.        ,  4.20408163,  4.40816327,  4.6122449 ,  4.81632653,
        5.02040816,  5.2244898 ,  5.42857143,  5.63265306,  5.83673469,
        6.04081633,  6.24489796,  6.44897959,  6.65306122,  6.85714286,
        7.06122449,  7.26530612,  7.46938776,  7.67346939,  7.87755102,
        8.08163265,  8.28571429,  8.48979592,  8.69387755,  8.89795918,
        9.10204082,  9.30612245,  9.51020408,  9.71428571,  9.91836735,
       10.12244898, 10.32653061, 10.53061224, 10.73469388, 10.93877551,
       11.14285714, 11.34693878, 11.55102041, 11.75510204, 11.95918367,
       12.16326531, 12.36734694, 12.57142857, 12.7755102 , 12.97959184,
       13.18367347, 13.3877551 , 13.59183673, 13.79591837, 14.        ])

In [43]:
arr4 = np.linspace(4, 40, 14)
arr4

array([ 4.        ,  6.76923077,  9.53846154, 12.30769231, 15.07692308,
       17.84615385, 20.61538462, 23.38461538, 26.15384615, 28.92307692,
       31.69230769, 34.46153846, 37.23076923, 40.        ])

### Step 5. Create a Random Numbered Array

In [45]:
# here the number of elements is given by rand() default range id 0 to 1 in decimal.

np.random.rand(4)

array([0.73573229, 0.47303999, 0.67089489, 0.39173179])

In [47]:
#  to create the 2D arrays

np.random.rand(4, 4)

array([[0.40567914, 0.65620519, 0.50736564, 0.47757496],
       [0.87184625, 0.36992295, 0.56445549, 0.9116648 ],
       [0.08324645, 0.61417738, 0.56790683, 0.85897225],
       [0.15703468, 0.51247654, 0.38423274, 0.96152137]])

### Step 6. Create a Random Integer Array

In [69]:
# here randint(start, end, size of the 1D array) 
#  we can also pass directly size not to write size not mendatotary like np.random.randint(4, 40, 4)

np.random.randint(4, 40, size = 4)

array([ 7, 28, 39, 37])

In [71]:
#  random integers for 2D array
# we can pass size in brackets to pass it as row and cok=lumn of the 2D array.

np.random.randint(4, 40, size = (4, 4))

array([[15, 20, 13, 11],
       [33,  5,  6, 33],
       [17, 16,  8,  7],
       [17, 33, 26, 29]])

### Step 7. Create a 1D Array and get Max,Min,ArgMax,ArgMin

In [89]:
arr1 = np.random.randint(4, 400, size = 10)
arr1


array([ 96, 151,  83,  86, 226, 246, 220, 314, 338,  76])

In [91]:
print(arr1.min())

76


In [93]:
print(arr1.max())

338


In [95]:
# return the index of the max element in our array 
print(arr1.argmax())

8


In [97]:
# return the index of the min element in our array
print(arr1.argmin())

9


### Step 8. Indexing in 1D Array

In [99]:
arr4 = np.random.randint(4, 40, size = 10)
arr4

array([36, 37, 39, 32,  8,  8, 25, 22, 37, 17])

In [101]:
arr4[5]

8

In [107]:
#  if we want to acces the elements in the range by the indexes
# first includes and the last one is excludeds
arr4[4 : 8]

array([ 8,  8, 25, 22])

### Step 9. Indexing in 2D Array

In [113]:
arr5 = np.random.randint(4, 40, size = (5, 5))
arr5

array([[18, 30, 19, 21, 10],
       [16, 35, 13, 25,  4],
       [12, 24, 28, 23, 33],
       [13, 18,  9, 21, 39],
       [21, 32, 32, 16, 38]])

In [115]:
arr5[1]

array([16, 35, 13, 25,  4])

In [125]:
#  if we want the row 16, 12, 13
arr5[1 : 4 ]

array([[16, 35, 13, 25,  4],
       [12, 24, 28, 23, 33],
       [13, 18,  9, 21, 39]])

In [129]:
#  we can also write arr[1][4]
arr5[1, 4]

4

### Step 10. Conditional Selection

In [131]:
arr6 = np.random.randint(20, 40 , size = 10)
arr6

array([31, 35, 22, 30, 20, 26, 22, 37, 20, 37])

In [143]:
arr6[arr6 > 25]


array([31, 35, 30, 26, 37, 37])

In [147]:
#  if we give the condition direct it return the array with boolean who satisfie the condition
arr6 > 35

array([False, False, False, False, False, False, False,  True, False,
        True])

In [145]:
arr6[arr6 < 35]

array([31, 22, 30, 20, 26, 22, 20])

In [149]:
#  to get the elements in the range we can do as below

arr6[(arr6 > 25) & (arr6 < 35)]

array([31, 30, 26])

### 🔥You did it! 10 exercises down — you're on fire! 🔥

## Pandas



### Step 1. Import the necessary libraries

In [151]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user). 

### Step 3. Assign it to a variable called users and use the 'user_id' as index

In [153]:
users = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user");
users

user_id|age|gender|occupation|zip_code
0                  1|24|M|technician|85711
1                       2|53|F|other|94043
2                      3|23|M|writer|32067
3                  4|24|M|technician|43537
4                       5|33|F|other|15213
..                                     ...
938                 939|26|F|student|33319
939           940|32|M|administrator|02215
940                 941|20|M|student|97229
941               942|48|F|librarian|78209
942                 943|22|M|student|77841

[943 rows x 1 columns]

In [155]:
#  to read clearly we can seperte the data
users = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user", sep = "|");
users


user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

In [157]:
#  here to make the user_id as the index we can do as below

users = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user", sep = "|", index_col="user_id");
users

age gender     occupation zip_code
user_id                                    
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
...      ...    ...            ...      ...
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

[943 rows x 4 columns]

### Step 4. See the first 25 entries

age gender     occupation zip_code
user_id                                    
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

In [186]:
users.head(25)

age gender     occupation zip_code
user_id                                    
1         24      M     technician    85711
2         53      F          other    94043
3         23      M         writer    32067
4         24      M     technician    43537
5         33      F          other    15213
6         42      M      executive    98101
7         57      M  administrator    91344
8         36      M  administrator    05201
9         29      M        student    01002
10        53      M         lawyer    90703
11        39      F          other    30329
12        28      F          other    06405
13        47      M       educator    29206
14        45      M      scientist    55106
15        49      F       educator    97301
16        21      M  entertainment    10309
17        30      M     programmer    06355
18        35      F          other    37212
19        40      M      librarian    02138
20        42      F      homemaker    95660
21        26      M         writer    30068
22        25      M         writer    40206
23        30      F         artist    48197
24        21      F         artist    94533
25        39      M       engineer    55107

### Step 5. See the last 10 entries

age gender     occupation zip_code
user_id                                    
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

In [163]:
users.tail(10)

age gender     occupation zip_code
user_id                                    
934       61      M       engineer    22902
935       42      M         doctor    66221
936       24      M          other    32789
937       48      M       educator    98072
938       38      F     technician    55038
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

### Step 6. What is the number of observations in the dataset?

943

In [167]:
users.shape[0]

943

### Step 7. What is the number of columns in the dataset?

4

In [172]:
users.shape[1]

4

### Step 8. Print the name of all the columns.

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

In [178]:
users.columns

Index(['age', 'gender', 'occupation', 'zip_code'], dtype='object')

### Step 9. How is the dataset indexed?

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
      dtype='int64', name='user_id', length=943)

In [180]:
users.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
      dtype='int64', name='user_id', length=943)

### Step 10. What is the data type of each column?

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

In [184]:
users.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

### Step 11. Print only the occupation column

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...      
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

In [188]:
#  users.occupation
users['occupation']

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...      
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

### Step 12. How many different occupations are in this dataset?

21

In [200]:
len(list(users.occupation.unique()))
# or
# users['occupatio'].nunique()

21

In [208]:
#  to get the name of occupations also
users['occupation'].unique()


array(['technician', 'other', 'writer', 'executive', 'administrator',
       'student', 'lawyer', 'educator', 'scientist', 'entertainment',
       'programmer', 'librarian', 'homemaker', 'artist', 'engineer',
       'marketing', 'none', 'healthcare', 'retired', 'salesman', 'doctor'],
      dtype=object)

### Step 13. What is the most frequent occupation?

occupation
student    196
Name: count, dtype: int64

In [210]:
#  here we get the number of people in the occupation default descending order
users['occupation'].value_counts()

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: count, dtype: int64

In [212]:
users['occupation'].value_counts().head(1)

occupation
student    196
Name: count, dtype: int64

In [214]:
#  to get the top 5 most frequent

users['occupation'].value_counts().head(5)

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
Name: count, dtype: int64

In [220]:
#  when we want the most frequent (not number just name of the occupation)

users['occupation'].value_counts().idxmax()

'student'

### Step 14. Summarize the DataFrame.

age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

In [222]:
#  here describe takes only numeric columns 

users.describe()

age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

### Step 15. Summarize all the columns

age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

In [226]:
#  to describe all solumns we have to pass the include = 'all'
users.describe(include = "all")

age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

### Step 16. Summarize only the occupation column

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

In [230]:
users['occupation'].describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### Step 17. What is the mean age of users?

34.05196182396607

In [235]:
users['age'].mean()

34.05196182396607

### Step 18. What is the age with least occurrence?

age
7     1
66    1
11    1
10    1
73    1
Name: count, dtype: int64

In [243]:
users['age'].value_counts().tail()

age
7     1
66    1
11    1
10    1
73    1
Name: count, dtype: int64

In [245]:
#  return the first least occurance oness
users['age'].value_counts().idxmin()

7

### You're not just learning, you're mastering it. Keep aiming higher! 🚀